eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/     # 向eureka服务中心注册

server:
  port: 8762

spring:
  application:
    name: eureka-client

    # 需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name